"""The domain-authoring path, executed rather than described.

`pgc_install/README.md` tells a domain developer what to write and how to build it. Prose about a
build path rots the moment the build changes, and nothing notices — this cycle found a governance
check, a warm-boot test and a provenance test that had each been wrong for months because nothing
ran them. So the guide is checked here instead: this script authors the smallest domain that admits
a request, does work and returns a result, then compiles, composes, boots and executes it.

It writes only to a temporary directory and installs nothing. Failure means the README is wrong.

Four things it pins, each of which was wrong when the guide was first written:

  * a domain must declare all five projection paths — omitting them survives GOVERN and CONSTRUCT
    and fails at S7, which reads as a compiler fault rather than a missing declaration;
  * `structure_scope` names the composed domain — set it generically and the snapshot composes a
    domain by that name, assembles, and conforms, wrongly named, with nothing to catch it;
  * a domain composes alongside the platform without violating the claimed profile;
  * the domain package must be importable at execution time, and when it is not the workflow returns
    VIOLATION with null outputs rather than raising — a missing module wearing a business refusal.

Run:  python .github/process/domain_authoring.py
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

WORKSPACE = Path(__file__).resolve().parents[2]
PLATFORM = WORKSPACE / "software_governance"
INSPECTOR = WORKSPACE / "snapshot_inspector"
PROFILES = WORKSPACE / ".github" / "snapshot_profiles"
PROFILE = "GOVERNANCE_SURFACE_PROFILE_V0"

PASS = FAIL = 0


def check(name: str, ok: bool, detail: str = "") -> None:
    global PASS, FAIL
    if ok:
        PASS += 1
        print(f"  ✅ {name}")
    else:
        FAIL += 1
        print(f"  ❌ {name}  {detail}")


def write(root: Path, rel: str, text: str) -> None:
    p = root / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(text, encoding="utf-8")


def run(args: list[str], env: dict) -> subprocess.CompletedProcess:
    return subprocess.run(args, capture_output=True, text=True, env={**os.environ, **env})


def author(root: Path) -> None:
    """The six files. Nothing here is generated by the toolchain — a domain is authored."""
    d = root / "greeting"
    write(d, "registry/structures/STRUCTURE_BUILD_GREETING_CONFIG_V0.md", """# STRUCTURE_BUILD_GREETING_CONFIG_V0

Build manifest for the `greeting` domain.

## Machine

```yaml
fqdn: greeting::STRUCTURE_BUILD_GREETING_CONFIG_V0
artifact_kind: STRUCTURE
version: V0
governed_by: structure::CONSTITUTION_STRUCTURE_V0
authority: pgc.platform
concern: greeting
structure_scope: greeting
reuse_visibility: business
core:
  summary: Build-time STRUCTURE manifest for the greeting domain
layer_definitions:
  GREETING:
    domain_subpath: registry
    registry_module: greeting.registry
    implementation_namespace: greeting.implementation.capability_transforms.atoms
    layer_category: domain
identity_rules:
- match: greeting.registry
  namespace: greeting
artifact_discovery:
  search_layers:
  - GREETING
  import_surface:
    domain: platform
  artifact_types:
  - AC
  - IN
  - WF
  - CC
  - CT
output_configuration:
  artifacts:
    layer: PROTOCOL_BUILD_ROOT
    subpath: compiled/canonical
  vocabulary_projection_path:
    layer: GOVERNANCE
    subpath: compiled/vocabulary
  tokenized_projection_path:
    layer: GOVERNANCE
    subpath: compiled/tokenized
  evidence_projection_path:
    layer: GOVERNANCE
    subpath: compiled/evidence
  trust_attestation_path:
    layer: GOVERNANCE
    subpath: compiled/trust
  visualization_projection_path:
    layer: GOVERNANCE
    subpath: compiled/visualization
  layer_outputs:
    GREETING:
      layer: GREETING
      subpath: compiled/canonical
```
""")
    write(d, "registry/greet/actors/AC_GREETER_V0.md", """# AC_GREETER_V0

The actor context under which a greeting is composed.

## Machine

```yaml
fqdn: greeting::AC_GREETER_V0
artifact_kind: ACTOR
version: v0
governed_by: actor::CONSTITUTION_ACTOR_IDENTITY_V0
authority: pgc.platform
concern: greeting
core:
  summary: Greeting domain actor
  description: System actor context under which the greeting workflow executes.
  type: system
  attributes:
    role:
      type: string
      required: true
      value: greeter
```
""")
    write(d, "registry/greet/intents/IN_GREETING_REQUESTED_V0.md", """# IN_GREETING_REQUESTED_V0

Admission gate for a greeting request.

## Machine

```yaml
fqdn: greeting::IN_GREETING_REQUESTED_V0
artifact_kind: INTENT
version: v0
governed_by: intent::CONSTITUTION_INTENT_V0
authority: pgc.platform
concern: greeting
core:
  summary: Validate a greeting request — a non-empty name
  workflow: WF_GREET_V0
  inputs:
    name:
      type: string
      required: true
      description: Who to greet
  outcomes:
    ACK:
      description: Request valid — execution proceeds
    NACK:
      description: Request invalid — execution rejected
extensions:
  domain: greeting.greet
  admission_rules:
  - name must be a non-empty string
```
""")
    write(d, "registry/greet/capability_transforms/CT_PURE_COMPOSE_GREETING_V0.md", """# CT_PURE_COMPOSE_GREETING_V0

Compose a greeting from a name.

## Machine

```yaml
fqdn: greeting::CT_PURE_COMPOSE_GREETING_V0
artifact_kind: CAPABILITY_TRANSFORM
version: v0
governed_by: capability_transforms::CONSTITUTION_CAPABILITY_TRANSFORMS_V0
authority: pgc.platform
concern: greeting
core:
  summary: Compose a greeting from a name
  refusal: returns
  description: Pure string composition. Returns the composed greeting.
  inputs:
    name:
      type: string
      required: true
      description: Who to greet
  outputs:
    greeting:
      type: string
      required: true
      description: The composed greeting
machine:
  ct_kind: atom
  ct_purity: ct_pure
  operation: PURE_COMPOSE_GREETING
  implementation:
    module: greeting.implementation.capability_transforms.atoms.ct_pure_compose_greeting_v0
    callable: execute
```
""")
    write(d, "registry/greet/capability_contracts/CC_COMPOSE_GREETING_V0.md", """# CC_COMPOSE_GREETING_V0

Compose a greeting.

## Machine

```yaml
fqdn: greeting::CC_COMPOSE_GREETING_V0
artifact_kind: CAPABILITY_CONTRACT
version: v0
governed_by: capability_contracts::CONSTITUTION_CAPABILITY_CONTRACT_V0
authority: pgc.platform
concern: greeting
core:
  summary: Compose a greeting for the requested name
  inputs:
    name:
      type: string
      required: true
  outputs:
    greeting:
      type: string
  result_status_contract:
    allowed:
    - SUCCESS
    - VIOLATION
    on_input_failure: VIOLATION
  pipeline:
  - step: compose
    transform: greeting::CT_PURE_COMPOSE_GREETING_V0
    inputs:
      name: $.inputs.name
    outputs:
      greeting: $.capability_result.greeting
    result_surface:
    - SUCCESS
    - VIOLATION
    on_result:
      SUCCESS: exit
      VIOLATION: exit
extensions:
  description: One pure transform, no side effect — the smallest contract that does work.
```
""")
    write(d, "registry/greet/workflows/WF_GREET_V0.md", """# WF_GREET_V0

Greet a named party.

## Machine

```yaml
fqdn: greeting::WF_GREET_V0
artifact_kind: WORKFLOW
version: v0
governed_by: workflow::CONSTITUTION_WORKFLOW_V0
authority: pgc.platform
concern: greeting
subdomain: greet
structure: execution::STRUCTURE_RUNTIME_EXECUTION_V0
core:
  summary: Admit a greeting request and compose the greeting
  actor_context: greeting::AC_GREETER_V0
  start_node: IN_GREETING_REQUESTED_V0
  nodes:
    IN_GREETING_REQUESTED_V0:
      type: IN
      code: IN_GREETING_REQUESTED_V0
      next:
        ACK: CC_COMPOSE_GREETING_V0
        NACK: EXIT_REJECTED
    CC_COMPOSE_GREETING_V0:
      type: CC
      code: CC_COMPOSE_GREETING_V0
      inputs:
        name: $.payload.name
      next:
        SUCCESS: EXIT_GREETED
        VIOLATION: EXIT_ERROR
    EXIT_GREETED:
      type: EXIT
      reason: COMPLETED
    EXIT_REJECTED:
      type: EXIT
      reason: EXITED
    EXIT_ERROR:
      type: EXIT
      reason: FAILED
```
""")
    for pkg in ("", "capability_transforms", "capability_transforms/atoms"):
        write(d, f"implementation/{pkg}/__init__.py".replace("//", "/"), "")
    write(d, "__init__.py", "")
    write(d, "implementation/capability_transforms/atoms/ct_pure_compose_greeting_v0.py",
          '"""CT_PURE_COMPOSE_GREETING_V0 — compose a greeting from a name."""\n\n\n'
          "class CTExecutionError(Exception):\n"
          '    """Raised when the transform cannot produce its declared outputs."""\n\n\n'
          "def execute(inputs, context=None):\n"
          '    name = (inputs or {}).get("name")\n'
          "    if not isinstance(name, str) or not name.strip():\n"
          '        raise CTExecutionError("name must be a non-empty string")\n'
          '    return {"greeting": f"Hello, {name.strip()}!"}\n')


def main() -> int:
    print("domain authoring — the path pgc_install/README.md documents\n")
    tmp = Path(tempfile.mkdtemp(prefix="pgc_domain_"))
    try:
        # The declaration repositories a domain author needs. `conformance_workloads` is
        # deliberately absent: the profile in force requires no workload, and this is what
        # establishes that rather than asserting it.
        ws = tmp / "ws"
        ws.mkdir()
        for src in (PLATFORM, INSPECTOR):
            shutil.copytree(src, ws / src.name,
                            ignore=shutil.ignore_patterns(".git", "snapshot", "__pycache__",
                                                          "build", "*.egg-info"))
        shutil.copytree(PROFILES, ws / "snapshot_profiles")
        author(tmp)

        env = {"PGC_PLATFORM_ROOT": str(ws / "software_governance"),
               "PGC_SNAPSHOT_PROFILES": str(ws / "snapshot_profiles")}
        py = sys.executable

        r = run([py, "-m", "compiler.cli", "compile", "--structure",
                 "STRUCTURE_BUILD_PLATFORM_CONFIG_V1"], env)
        check("platform_compiles_without_workloads", "0 failed" in r.stdout,
              "the profile requires no workload, so its repository should not be needed")

        r = run([py, "-m", "compiler.cli", "compile", "--structure",
                 "STRUCTURE_BUILD_INSPECTION_CONFIG_V0"],
                {**env, "PGC_DOMAIN_ROOTS": str(ws / "snapshot_inspector"),
                 "PGC_SNAPSHOT_ROOT": str(ws / "snapshot_inspector" / "snapshot")})
        check("inspection_compiles", "0 failed" in r.stdout)

        r = run([py, "-m", "compiler.cli", "compile", "--structure",
                 "STRUCTURE_BUILD_GREETING_CONFIG_V0"],
                {**env, "PGC_DOMAIN_ROOTS": str(tmp / "greeting"),
                 "PGC_SNAPSHOT_ROOT": str(tmp / "greeting" / "snapshot")})
        check("authored_domain_compiles", "0 failed" in r.stdout,
              (r.stdout + r.stderr)[-400:])
        if "0 failed" not in r.stdout:
            return 1

        snap = tmp / "snapshot"
        r = run([py, "-m", "assembler.cli", "assemble",
                 "--source", str(ws / "software_governance" / "snapshot" / "compiled"),
                 "--source", str(ws / "snapshot_inspector" / "snapshot" / "compiled"),
                 "--source", str(tmp / "greeting" / "snapshot" / "compiled"),
                 "--out", str(snap), "--profile", PROFILE], env)
        out = r.stdout + r.stderr
        check("composes_without_violating_the_profile", "composition: PASSED" in out, out[-300:])

        # The composed domain is named by `structure_scope`. A generic value assembles and conforms
        # under the wrong name, so the name is asserted rather than assumed.
        manifest = json.loads((snap / "manifest.json").read_text())
        domains = sorted(d["domain"] for d in manifest["domains"])
        check("structure_scope_names_the_domain", domains == ["greeting", "inspection", "platform"],
              f"composed {domains}")

        r = run([py, "-m", "runtime.cli", "boot", "--snapshot", str(snap)], env)
        check("boots", "healthy" in (r.stdout + r.stderr), (r.stdout + r.stderr)[-200:])

        payload = tmp / "payload.json"
        payload.write_text(json.dumps({"name": "world"}))
        run_args = [py, "-m", "runtime.cli", "run", "--wf", "greeting::WF_GREET_V0",
                    "--payload", str(payload), "--snapshot", str(snap),
                    "--data-root", str(tmp / "data")]

        # Not importable: the runtime imports the module a CT names, and when it cannot the
        # workflow refuses rather than raising. A missing module wearing a business refusal is
        # the failure a domain author is most likely to misread.
        r = run(run_args, env)
        check("uninstalled_domain_refuses_rather_than_raising",
              "VIOLATION" in (r.stdout + r.stderr), (r.stdout + r.stderr)[-200:])

        r = run(run_args, {**env, "PYTHONPATH": str(tmp)})
        out = r.stdout + r.stderr
        check("executes_when_importable", "SUCCESS" in out and "Hello, world!" in out, out[-300:])
    finally:
        shutil.rmtree(tmp, ignore_errors=True)

    print(f"\nPASSED: {PASS}/{PASS + FAIL}")
    return 1 if FAIL else 0


if __name__ == "__main__":
    sys.exit(main())
